name: Detect breaking OpenAPI changes with OpenAPI Diff
on:
  # push:
  pull_request:
  workflow_dispatch:

jobs:
  openapi-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth:

      - name: Install @azure/oad package
        run: npm i @azure/oad

      - name: Fetch main branch
        run: git fetch origin main

      - name: Get changed files
        uses: dorny/paths-filter@v3
        id: changed_files
        with:
          list-files: shell
          filters: |
            openapi:
              - 'environments/prod/apis/**' 
              - 'environments/staging/apis/**'

      - name: Install oasdiff
        if: ${{ steps.changed_files.outputs.openapi_files }} != ''
        run: curl -fsSL https://raw.githubusercontent.com/oasdiff/oasdiff/main/install.sh | sh

      # - name: Detect changes in OpenAPI spec
      #   if: ${{ steps.changed_files.outputs.openapi_files }} != ''
      #   run: |
      #     for file in ${{ steps.changed_files.outputs.openapi_files }}; do
      #       if [[ $file == *.json ]]; then
      #         echo "CHANGED FILE VERSION:"
      #         cat $file
      #         echo "\n\nORIGINAL VERSION FROM MAIN:"
      #         git show origin/main:"$file" || echo "File $file not found in main"
      #       fi
      #     done
      #   shell: bash

      - name: Detect changes in OpenAPI spec
        if: ${{ steps.changed_files.outputs.openapi_files }} != ''
        id: oasdiff
        run: |
          report=""
          for file in ${{ steps.changed_files.outputs.openapi_files }}; do
            if [[ $file == *.json ]]; then
              git show origin/main:"$file" > /tmp/original.json || touch /tmp/original.json
              oasdiff changelog -f githubactions "$file" /tmp/original.json
              out=$(oasdiff changelog -f markdown "$file" /tmp/original.json)
              report="${report}\n${out}"
            fi
          done
          echo -e "report<<EOF\n${report}\nEOF" >> $GITHUB_OUTPUT
        shell: bash

      - name: Create or update PR comment with OAS Diff findings
        if: ${{ steps.changed_files.outputs.openapi_files }} != ''
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ${{ steps.oasdiff.outputs.report }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

