name: Detect breaking OpenAPI changes with OpenAPI Diff
on:
  # push:
  pull_request:
  workflow_dispatch:

jobs:
  openapi-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth:

      - name: Fetch main branch
        run: git fetch origin main

      - name: Get changed files
        uses: dorny/paths-filter@v3
        id: changed_files
        with:
          list-files: shell
          filters: |
            openapi:
              - 'environments/prod/apis/**' 
              - 'environments/staging/apis/**'

      - run: |
          for file in ${{ steps.changed_files.outputs.openapi_files }}; do
            if [[ $file == *.json ]]; then
              echo "CHANGED FILE VERSION:"
              cat $file
              echo "\n\nORIGINAL VERSION FROM MAIN:"
              git show origin/main:"$file" || echo "File $file not found in main"
            fi
          done
        shell: bash


