name: Infra deployment with Terragrunt
on:
  pull_request:
  workflow_dispatch:

env:
  tf_version: '1.11.3'
  tg_version: '0.63.6'

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main

      - name: Plan
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: ./environments/staging/base
          tg_command: 'plan'