name: Check OpenAPI Spec with Checkov
on:
  # push:
  # pull_request:
  workflow_dispatch:

jobs:
  checkov-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: dorny/paths-filter@v3
        id: changed_files
        with:
          list-files: shell
          filters: |
            openapi:
              - 'environments/prod/apis/**'
              - 'environments/staging/apis/**'

      - name: Install Checkov
        run: pip install checkov

      - run: echo '${{ steps.changed_files.outputs.openapi_files }}'

      - name: Run Checkov on changed JSON files in apis folder
        if: ${{ steps.changed_files.outputs.openapi_files }} != ''
        run: |
          for file in ${{ steps.changed_files.outputs.openapi_files }}; do
            if [[ $file == *.json ]]; then
              checkov -f "$file" --framework openapi --quiet --skip-check CKV_OPENAPI_2 --skip-check CKV_OPENAPI_3
            fi
          done
        shell: bash