name: Check OpenAPI Spec with Checkov
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  checkov-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: dorny/paths-filter@v3
        id: changed_files
        with:
          list-files: shell
          filters: |
            openapi:
              - 'environments/prod/apis/**'
              - 'environments/staging/apis/**'

      - name: Install Checkov
        run: pip install checkov

      - run: echo '${{ steps.changed_files.outputs.openapi_filter }}'

    # - name: Run Checkov on changed JSON files in apis folder
    #   run: |
    #     echo '${{ steps.files.outputs.all }}' | jq -r '.[]' | grep '^apis/.*\.json$' | while read file; do
    #       echo "Running Checkov on $file"
    #       checkov -f "$file" --framework openapi
    #     done
    #   shell: bash